### ISSUE TITLE
Type IOError has no field code

### ISSUE THREAD

**Issue by mattBrzezinski** [JuliaCloud/AWS.jl#527] opened 2021-12-06 19:11 UTC
Saw this in conjunction of [CloudWatchLogs.jl](https://github.com/invenia/CloudWatchLogs.jl/). Stack trace below,

```julia
2021-12-06T11:42:14.386-06:00	[2021-12-06 17:42:14 | {REDACTED} | warn | CloudWatchLogs]: type IOError has no field code
2021-12-06T11:42:14.386-06:00	Stacktrace:
2021-12-06T11:42:14.386-06:00	[1] getproperty(x::HTTP.IOExtras.IOError, f::Symbol)
2021-12-06T11:42:14.386-06:00	@ Base ./Base.jl:33
2021-12-06T11:42:14.386-06:00	[2] macro expansion
2021-12-06T11:42:14.386-06:00	@ ~/.julia/packages/Retry/vS1bg/src/repeat_try.jl:110 [inlined]
2021-12-06T11:42:14.386-06:00	[3] submit_request(aws::AWSConfig, request::Request; return_headers::Nothing)
2021-12-06T11:42:14.386-06:00	@ AWS ~/.julia/packages/AWS/nUGJF/src/utilities/request.jl:85
2021-12-06T11:42:14.386-06:00	[4] (::JSONService)(operation::String, args::Dict{String, Any}; aws_config::AWSConfig, feature_set::AWS.FeatureSet)
2021-12-06T11:42:14.386-06:00	@ AWS ~/.julia/packages/AWS/nUGJF/src/AWS.jl:376
2021-12-06T11:42:14.386-06:00	[5] put_log_events(logEvents::Vector{CloudWatchLogs.LogEvent}, logGroupName::String, logStreamName::String, params::Dict{String, String}; aws_config::AWSConfig)
2021-12-06T11:42:14.386-06:00	@ CloudWatchLogs.CloudWatch_Logs ~/.julia/packages/AWS/nUGJF/src/services/cloudwatch_logs.jl:1405
2021-12-06T11:42:14.386-06:00	[6] _put_log_events(stream::CloudWatchLogs.CloudWatchLogStream, events::Vector{CloudWatchLogs.LogEvent})
2021-12-06T11:42:14.386-06:00	@ CloudWatchLogs ~/.julia/packages/CloudWatchLogs/gXZUD/src/stream.jl:199
2021-12-06T11:42:14.386-06:00	[7] macro expansion
2021-12-06T11:42:14.386-06:00	@ ~/.julia/packages/Mocking/MsKoy/src/mock.jl:29 [inlined]
2021-12-06T11:42:14.386-06:00	[8] #19
2021-12-06T11:42:14.386-06:00	@ ~/.julia/packages/CloudWatchLogs/gXZUD/src/stream.jl:290 [inlined]
2021-12-06T11:42:14.386-06:00	[9] (::Base.var"#70#72"{Base.var"#70#71#73"{ExponentialBackOff, CloudWatchLogs.var"#retry_cond#23"{CloudWatchLogs.CloudWatchLogStream}, CloudWatchLogs.var"#19#25"{CloudWatchLogs.CloudWatchLogStream, Vector{CloudWatchLogs.LogEvent}}}})(; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
2021-12-06T11:42:14.386-06:00	@ Base ./error.jl:288
2021-12-06T11:42:14.386-06:00	[10] #70
2021-12-06T11:42:14.386-06:00	@ ./error.jl:284 [inlined]
2021-12-06T11:42:14.386-06:00	[11] submit_logs(stream::CloudWatchLogs.CloudWatchLogStream, events::Vector{CloudWatchLogs.LogEvent})
2021-12-06T11:42:14.386-06:00	@ CloudWatchLogs ~/.julia/packages/CloudWatchLogs/gXZUD/src/stream.jl:296
2021-12-06T11:42:14.386-06:00	[12] macro expansion
2021-12-06T11:42:14.386-06:00	@ ~/.julia/packages/Mocking/MsKoy/src/mock.jl:29 [inlined]
2021-12-06T11:42:14.386-06:00	[13] process_available_logs!(handler::CloudWatchLogs.CloudWatchLogHandler{DefaultFormatter})
2021-12-06T11:42:14.386-06:00	@ CloudWatchLogs ~/.julia/packages/CloudWatchLogs/gXZUD/src/handler.jl:73
2021-12-06T11:42:14.386-06:00	[14] process_logs!(handler::CloudWatchLogs.CloudWatchLogHandler{DefaultFormatter})
2021-12-06T11:42:14.386-06:00	@ CloudWatchLogs ~/.julia/packages/CloudWatchLogs/gXZUD/src/handler.jl:94
2021-12-06T11:42:14.386-06:00	[15] (::CloudWatchLogs.var"#29#30"{CloudWatchLogs.CloudWatchLogHandler{DefaultFormatter}})()
2021-12-06T11:42:14.386-06:00	@ CloudWatchLogs ./task.jl:411
```

**Comment by iamed2** [comment] 2022-01-19 22:49
Closing as dupe of https://github.com/JuliaCloud/AWS.jl/issues/506, reopen if there is an issue in AWS.jl versions past 1.68.1

**Closed by iamed2** 2022-01-19 22:49 UTC
Labels: bug, good-first-issue
